name: Linting, formatting and Build on PR
on:
  pull_request:
    branches:
      - dev

jobs:
  Continuous-Integration:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn --legacy-peer-deps

      - name: Run linting check
        run: yarn run lint:check

      - name: Check formatting
        run: yarn run format:check

      - name: Build
        run: yarn run build
